# Войтешонок Вячеслав №3

In [1]:
import numpy as np

In [2]:
n = 5
b = np.ones(n) * 4.2
C = np.array([[0.2, 0, 0.2, 0, 0],
              [0, 0.2, 0, 0.2, 0],
              [0.2, 0, 0.2, 0, 0.2],
              [0, 0.2, 0, 0.2, 0],
              [0, 0, 0.2, 0, 0.2]])

d = np.array([2.33, 0.81, 0.67, 0.92, -0.53])
D = []
for i in range(n):
    j, temp = i, []
    for k in range(n):
        temp.append(d[(k-j)%n])
    D.append(temp)
A = np.array(D)
A += 3*C

In [3]:
def gauss(A, b, n):
    #прямой ход
    for i in range(n):
        if A[i][i]==0:
            continue
        temp = A[i][i]
        for j in range(i, n):
            A[i][j] /= temp
        b[i] /= temp
        for j in range(i+1, n):
            b[j] -= b[i]*A[j][i]
            A[j] -= A[i]*A[j][i]
    print(f"A: {A}")
    print(f"b: {b}")
    #обратный ход
    X = []
    for i in range(n):
        for j in range(i):
            b[n-1-i] -= X[j]*A[n-1-i][n-j-1]
        X.append(b[n-i-1])
    X.reverse()
    print(f"X: {X}")

In [4]:
gauss(A.copy(), b.copy(), n)

A: [[ 1.          0.27645051  0.4334471   0.31399317 -0.18088737]
 [ 0.          1.          0.33795567  0.46689667  0.26787735]
 [ 0.          0.          1.          0.29949526  0.69416959]
 [ 0.          0.          0.          1.          0.58786529]
 [ 0.          0.          0.          0.          1.        ]]
b: [1.4334471  1.61212309 1.37060703 1.14260562 0.79881835]
X: [0.8580235922969008, 0.8762290087200716, 0.6145289054773782, 0.673008038473097, 0.7988183544239552]


In [5]:
from scipy import linalg
linalg.solve(A, b)

array([0.85802359, 0.87622901, 0.61452891, 0.67300804, 0.79881835])

In [6]:
def major(A, b, n):
    #прямой ход
    for i in range(n):
        a = A[i:, i]
        temp = a.max()
        if temp==0:
            continue
        max_row = np.where(a == temp)[0][0]
        #print(f"a{i}: {a}\n max = {temp}\n row = {max_row}")
        A[[i, i+max_row]]=A[[i+max_row, i]]
        b[[i, i+max_row]]=b[[i+max_row, i]]
        for j in range(i, n):
            A[i][j] /= temp
        b[i] /= temp
        for j in range(i+1, n):
            b[j] -= b[i]*A[j][i]
            A[j] -= A[i]*A[j][i]
        #print(f"A{i}: {A}")
    print(f"A: {A}")
    print(f"b: {b}")
    #обратный ход
    X = []
    for i in range(n):
        for j in range(i):
            b[n-1-i] -= X[j]*A[n-1-i][n-j-1]
        X.append(b[n-i-1])
    X.reverse()
    print(f"X: {X}")

In [7]:
major(A.copy(), b.copy(), n)

A: [[ 1.          0.27645051  0.4334471   0.31399317 -0.18088737]
 [ 0.          1.          0.33795567  0.46689667  0.26787735]
 [ 0.          0.          1.          0.29949526  0.69416959]
 [ 0.          0.          0.          1.          0.58786529]
 [ 0.          0.          0.          0.          1.        ]]
b: [1.4334471  1.61212309 1.37060703 1.14260562 0.79881835]
X: [0.8580235922969008, 0.8762290087200716, 0.6145289054773782, 0.673008038473097, 0.7988183544239552]


In [8]:
x = [0.8580235922969008, 0.8762290087200716, 0.6145289054773782, 0.673008038473097, 0.7988183544239552]

In [9]:
np.around(x, 3)

array([0.858, 0.876, 0.615, 0.673, 0.799])