In [1]:
import numpy as np
import math

In [2]:
C = np.array([
    [0.2, 0, 0.2, 0, 0],
    [0, 0.2, 0, 0.2, 0],
    [0.2, 0, 0.2, 0, 0.2],
    [0, 0.2, 0, 0.2, 0],
    [0, 0, 0.2, 0, 0.2],
])

D = np.array([
    [2.33, 0.81, 0.67, 0.92, -0.53],
    [0.81, 2.33, 0.81, 0.67, 0.92],
    [0.67, 0.81, 0.23, 0.81, 0.92],
    [0.92, 0.67, 0.81, 2.33, -0.53],
    [-0.53, 0.92, 0.92, -0.53, 2.33]
])

A = 3 * C + D

In [3]:
def find_i_j(A):
    i, j = 0, 1
    for ii in range(0, len(A[0])):
        for jj in range(ii+1, len(A[0])):
            if A[ii][jj] > A[i][j]:
                i, j = ii, jj
    return i, j

In [4]:
A = np.array([
    [5, 1, 2],
    [1, 4, 1],
    [2, 1, 3]
])

In [50]:
A = np.array([
    [2, 1],
    [1, 3]
])

In [7]:
EPS = 1e-4

In [8]:
v = np.eye(A.shape[0])
k = 0
while abs(A[find_i_j(A)[0]][find_i_j(A)[1]])>EPS:
    i, j = find_i_j(A)
    phi = 1/2 * math.atan(2 * A[i][j] / (A[i][i]- A[j][j]))
    H = np.eye(A.shape[0])
    H[i][i] = H[j][j] = np.cos(phi)
    H[j][i] = H[i][j] = np.sin(phi)
    H[i][j] *= -1
    v = v.dot(H)
    A = (H.T.dot(A)).dot(H)
    k += 1
print(k)

5


In [9]:
A

array([[ 6.89510652e+00,  0.00000000e+00, -4.61723423e-06],
       [-4.51028104e-17,  3.39729482e+00, -6.54397066e-04],
       [-4.61723423e-06, -6.54397066e-04,  1.70759867e+00]])

In [10]:
v

array([[ 0.75257541, -0.45812708, -0.47302201],
       [ 0.43170398,  0.8856695 , -0.17094212],
       [ 0.49725438, -0.07555865,  0.86430837]])

In [11]:
for i in range(v.shape[0]):
    print(v[:,  i])

[0.75257541 0.43170398 0.49725438]
[-0.45812708  0.8856695  -0.07555865]
[-0.47302201 -0.17094212  0.86430837]


In [12]:
for i in range(A.shape[0]):
    print(A[i][i])

6.895106515923419
3.3972948158577623
1.7075986682188165
